#ifndef LDM_H_included
#define LDM_H_included

/**
 * @file ldm.h
 *
 * @brief Library for manipulating LDM files.
 *
 * @todo use stdint.h variables to ensure correct lenght
 */

/**
 * @defgroup ldm LDM library
 *
 * Library for manipulating with LDM files. LDM files are loader
 * modules intended to be used as input for bootloader. LDM files are
 * generated by linker, they contain statically linked program with all
 * libraries. Content of LDM file should be relocated, in order to do so,
 * each memory item have flag, if this flags is set item is instruction
 * with direct address in operand that should be retarget.
 *
 * Example ussage of this library is as follow:
 * @code
 * ldm_buffer_item_t * buffer;
 *
 * ldm_load("input_file.ldm", &buffer);
 *
 * printf("------------------------\nPrinting buffer:\n\n");
 * for(ldm_buffer_item_t *p = buffer;p!=NULL;p=p->next){
 *     printf("Address:    0x%x\n", p->address);
 *     printf("Value:      0x%x\n", p->value);
 *     printf("Relocation: 0x%d\n\n", p->relocation);
 * }
 * printf("Done.\n------------------------\n");
 *
 * ldm_write("output_file.ldm", buffer);
 *
 * free_ldm_buffer(buffer);
 * @endcode
 *
 * @addtogroup ldm
 *
 * @{
 */

#include <stdio.h>

/**
 * @brief Error codes
 *
 * Error codes are returnet by function get_ldmlib_errno() and can
 * be used to get more information about potential error.
 */
typedef enum{
    LDMERR_OK = 0,              /**< @brief Ewerithing is ok ... have a nice day :) */
    LDMERR_BAD_LDM_FORMAT,      /**< @brief LDM file have bad format. */
    LDMERR_FILE_OPEN_ERROR,     /**< @brief Error when openning LDM file.*/
    LDMERR_LINE_READ_FAILED,    /**< @brief Error on reading line from LDM file.*/
    LDMERR_READING_EMPTY_LINE,  /**< @brief Empty line was readed from LDM file.*/
    LDMERR_CLEAR_EMPTY_BUFFER,  /**< @brief Trying to free empty buffer.*/
    LDMERR_FILE_NOT_OPENNED,    /**< @brief Was about to read file but file is not opened.*/
    LDMERR_WRITING_FAILED,      /**< @brief Returned when writing to LDM file failed.*/
    LDMERR_MALLOC_FAILED        /**< @brief Error when trying to allocate memory from heap. */
} tLdmError;

/**
 * @brief Structure for operating with items in ldm file.
 *
 * When LDM file is parsed, by ldm_load() function, linked list based on
 * this structure is generated. One instance of this structure hold
 * exactly one line in LDM file.
 *
 * When writing LDM files from scratch, you have to create linked list
 * with content of the LDM file by your own. Pointer to the base of that
 * list is then given to ldm_write() function.
 *
 * @note This structure hold exactly one line from LDM. LDM library don't
 * care if it is valid instruction or plain binary data (for example variables).
 */
typedef struct ldm_buffer_item_s{
    unsigned int address; /**< @brief Address of the item parsed from LDM file. */
    unsigned int value;  /**< @brief Value of the item. */
    unsigned int relocation; /**< @brief Retarget flag. */
    struct ldm_buffer_item_s * next; /**< @brief Pointer to the next item. It is linked list.*/
}ldm_buffer_item_t;

/**
 * @brief Open and parse ldm file.
 *
 * @param filename Name of the file that should be readed.
 * @param b Buffer where content of file will be stored.
 *
 * @return -1 in case of error, 0 on succes
 */
int ldm_load(char* filename, ldm_buffer_item_t** b);

/**
 * @brief Write ldm file.
 *
 * @param filename Name of the file that should be written.
 * @param b Pointer to buffer whitch will be written to the file.
 *
 * @return -1 in case of error, 0 on succes
 *
 * @note If file already exist it will be overwritten!
 */
int ldm_write(char* filename, ldm_buffer_item_t* b);

/**
 * @brief Clean up after buffer.
 *
 * Buffer should be allocated on the heap dynamically. For that
 * purpose use malloc as usual. But when you want to free
 * allocated memmory, you can use this function to do it.
 *
 * @param b Pointer to base of buffer.
 *
 * @return -1 in case of error, 0 on succes
 */
int free_ldm_buffer(ldm_buffer_item_t* b);

/**
 * @brief Return last error code.
 *
 * @note Errno variable is simple variable, this function
 * will not clean it after reading. If you call this function
 * you have to call clear_ldmlib_errno() too in order to be
 * able catch next error.
 *
 * @return Error code.
 */
tLdmError get_ldmlib_errno(void);

/**
 * @brief Clean errno variable.
 *
 * For more informations please refer get_ldmlib_errno()
 */
void clear_ldmlib_errno(void);

/**
 * @}
 */

#endif
