#ifndef MIF_H_included
#define MIF_H_included

/**
 * @file mif.h
 *
 * @brief Library for dealing with MIF files
 *
 * @todo Add support for all mif features.
 * @todo Add list of supported features.
 */

/**
 * @defgroup mif MIF library
 *
 * This library is intended fow manipulating with Intel Quartus mif
 * files. These files are used to initialize content of memory blocks,
 * in the FPGA design.
 *
 * Example ussage of this library is as follow:
 * @code
 * mif_buffer_item_t * buffer;
 *
 * mif_read("input_file.mif", &buffer);
 *
 * printf("------------------------\nPrinting buffer:\n\n");
 * for(mif_buffer_item_t *p = buffer;p!=NULL;p=p->next){
 *     printf("Address:    0x%x\n", p->address);
 *     printf("Value:      0x%x\n", p->value);
 * }
 * printf("Done.\n------------------------\n");
 *
 * mif_write("output_file.mif", buffer);
 *
 * free_mif_buffer(buffer);
 * @endcode
 *
 * @note Not all features that mif files can have are implemented. Library
 * is able to read mif file generated by library itself, and Quartus
 * will read it as well. But not every mif file generated by Quartus will
 * be readable by this library.
 *
 * @addtogroup mif
 *
 * @{
 */

#include <stdint.h>

/**
 * @brief Error codes
 *
 * Error codes are returnet by function get_miflib_errno() and can
 * be used to get more information about error.
 */

typedef enum{
    MIFERR_OK = 0,              /**< @brief Nothing special... */
    MIFERR_FILE_OPEN_ERROR,     /**< @brief Can't open mif file for several reasons. */
    MIFERR_BAD_MIF_FORMAT,      /**< @brief Mif file isn't in correct format. */
    MIFERR_MALLOC_FAILED,       /**< @brief Failed to allocate memory for mif item. */
    MIFERR_READING_EMPTY_LINE,  /**< @brief Empty line was readed when parsing file. This may not be an error.*/
    MIFERR_LINE_READ_FAILED,    /**< @brief Failed when reading line. */
    MIFERR_END_OF_FILE,         /**< @brief Reached end of mif file. */
    MIFERR_CLEAR_EMPTY_BUFFER   /**< @brief You want to creal empty buffer. */
} tMifError;

/**
 * @brief Structure to hold items from mif.
 */
typedef struct mif_buffer_item_s{
    uint32_t address;                   /**< @brief Address of item from mif file. */
    uint32_t value;                     /**< @brief Value of the item from mif file. */
    struct mif_buffer_item_s* next;     /**< @brief Pointer to the next item, buffer is linked list. */
}mif_buffer_item_t;

/**
 * @brief Return last error code.
 *
 * @note Errno variable is simple variable, this function
 * will not clean it after reading. If you call this function
 * you have to call clear_miflib_errno() too in order to be
 * able catch next error.
 *
 * @return Error code.
 */
tMifError get_miflib_errno(void);

/**
 * @brief Clean errno variable.
 *
 * For more informations please refer get_miflib_errno()
 */
void clear_miflib_errno(void);

/**
 * @brief Read mif file
 *
 * Read given mif file. Parse it and store its content into
 * buffer mif_buffer.
 *
 * This function also allocate memory for buffer, parse just pointer to
 * it.
 *
 * @return -1 on failure otherwise 0
 */
int mif_load(char * filename, mif_buffer_item_t** mif_buffer);

/**
 * @brief write mif file.
 *
 * Write given mif_buffer itno mif file. You have only specify name of
 * the file. Others parameters will be calculated automatically.
 *
 * Buffer of mif item you have create manually. Use malloc to allocate
 * memory for mif structures and build linked list of mif_buffer_item_t
 * structures.
 *
 * @return -1 on failure otherwise 0
 */
int mif_write(char * filename, mif_buffer_item_t* mif_buffer);

/**
 * @brief free memory after buffer.
 *
 * Buffer is stored at stack, you have to call this function in order to
 * free used memory. Otherwive you will suffer memory leak!
 *
 * @return -1 on failure otherwise 0
 */
int free_mif_buffer(mif_buffer_item_t* mif_buffer);

/**
 * @}
 */

#endif
