/**
 * @file objread.c
 *
 * @brief Utility for reading object files.
 *
 * @author Bc. Vladislav Mlejnecký <v.mlejnecky@seznam.cz>
 * @date 15.06.2019
 *
 * @note This file is part of m2tools project.
 *
 * @todo Write short manual how to use this tool. For what is used and simple overview how it work.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include <stdbool.h>

#include <obj.h>
#include <isa.h>

typedef struct{
    char *i_file;
    bool print_symbols;
    bool print_symbol_vals;
    bool print_data;
}settings_t;

#define HELP_STRING "\
Example usage: \n\
 "PROG_NAME" main.o\n\
\n\
        This is simple objread utility for "TARGET_ARCH_NAME" CPU that can be used\n\
    to show content of object files generated by assembler.\n\
\n\
Arguments:\n\
    -h --help           Print this help.\n\
       --version        Print version number and exit.\n\
    -s --symbol-table   Print symbol table.\n\
       --symbol-values  Print values of symbol in the symbol table. This\n\
                        enable printing of the symbol table too.\n\
    -a --all            Print everything.\n\
       --data           Print data stored in sections.\n"

static void arg_parse(int argc, char* argv[]);
static void print_version(void);
static void print_help(void);
static void clean_mem(void);

static settings_t settings;
obj_file_t *obj_file = NULL;

static const char * EXPORT_TEXT = "export";
static const char * IMPORT_TEXT = "import";

int main(int argc, char* argv[]){

    atexit(clean_mem);

    //get args
    arg_parse(argc, argv);

    if(!obj_load_from_file(settings.i_file, &obj_file)){
        fprintf(stderr, "Failed to load object file! obj_lib errno: %d\n", get_objlib_errno());
        exit(EXIT_FAILURE);
    }

    printf("Object file from: '%s'\n", settings.i_file);

    printf(" |- Object name: '%s'\n", obj_file->object_file_name);

    for(section_t* section = obj_file->first_section; section != NULL; section = section->next){
        if(section->next != NULL) printf(" |- Section: '%s'\n", section->section_name);
        else printf(" '- Section: '%s'\n", section->section_name);

        if(settings.print_symbols == true){
            char c_for_symbol_table = '\'';
            char c_for_section = '|';

            if(settings.print_data == true) c_for_symbol_table = '|';
            if(section->next == NULL) c_for_section = ' ';

            printf(" %c  %c- Symbol table:\n", c_for_section, c_for_symbol_table);

            for(spec_symbol_t *symbol = section->spec_symbol_first; symbol != NULL; symbol = symbol->next){
                char c = '|';
                char cc = ' ';
                const char *s = EXPORT_TEXT;

                if(symbol->next == NULL) c = '\'';
                if(settings.print_data == true) cc = '|';
                if(symbol->type == SYMBOL_IMPORT) s = IMPORT_TEXT;

                if(settings.print_symbol_vals == false){
                    printf(" %c  %c  %c- '%s' %s\n", c_for_section, cc, c, symbol->name, s);
                }
                else{
                    printf(" %c  %c  %c- '%s' "PRIisa_addr" %s\n", c_for_section, cc, c, symbol->name, symbol->value, s);

                }
            }

        }

        if(settings.print_data == true){
            if(section->next != NULL) printf(" |  '- Data:\n");
            else printf("    '- Data:\n");

            for(data_symbol_t *data = section->data_first; data != NULL; data = data->next){
                char c = '|';

                if(data->next == NULL) c = '\'';

                if(section->next != NULL) printf(" |     %c- ", c);
                else printf("       %c- ", c);

                if(data->type == DATA_IS_BLOB){
                    printf("Blob: ");

                    printf("Off:"PRIisa_addr" Len:%dB\n", data->address, data->payload.blob->lenght);
                }
                else{
                    printf("Inst: ");

                    printf("Off:"PRIisa_addr" Opc:0x%"PRIX32" r:%s s:%s\n", data->address, data->payload.inst->word, data->relocation ? "true" : "false" , data->special ? "true" : "false");
                }


            }
        }
    }

    return EXIT_SUCCESS;
}

static void arg_parse(int argc, char* argv[]){
    settings.i_file = NULL;
    settings.print_symbols = false;
    settings.print_symbol_vals = false;
    settings.print_data = false;

    int file_given = 0;
    int toomuchfiles_given = 0;

    for(int i = 1; i<argc; i++){
        if(strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0 ){
            print_help();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "--version") == 0 ){
            print_version();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "-s") == 0 || strcmp(argv[i], "--symbol-table") == 0 ){
            settings.print_symbols = true;
        }
        else if(strcmp(argv[i], "--symbol-values") == 0 ){
            settings.print_symbol_vals = true;
            settings.print_symbols = true;
        }
        else if(strcmp(argv[i], "-a") == 0 || strcmp(argv[i], "--all") == 0 ){
            settings.print_symbol_vals = true;
            settings.print_symbols = true;
            settings.print_data = true;
        }
        else if(strcmp(argv[i], "--data") == 0 ){
            settings.print_data = true;
        }
        else{
            if(argv[i][0] != '-'){
                if(file_given == 0){
                    settings.i_file = argv[i];
                    file_given = 1;
                }
                else{
                    toomuchfiles_given = 1;
                }
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
    }

    if(file_given == 0){
        fprintf(stderr, "Missing input file!\n");
        exit(EXIT_FAILURE);
    }
    if(toomuchfiles_given == 1){
        fprintf(stderr, "Too much input files given!\n");
        exit(EXIT_FAILURE);
    }

}

static void print_version(void){
    printf("objdump for %s CPU %s\n", TARGET_ARCH_NAME, VERSION);
}

static void print_help(void){
    printf(HELP_STRING);
}

static void clean_mem(void){
    if(obj_file != NULL){
        free_object_file(obj_file);
    }
}

