/**
 * @file linker.c
 *
 * @brief Tool for linking object files together.
 *
 * @author Bc. Vladislav Mlejnecký <v.mlejnecky@seznam.cz>
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

static void print_version(void);
static void print_help(void);
static void arg_parse(int argc, char* argv[]);

#define HELP_STRING "\
Example usage: \n\
 "PROG_NAME"\n\
\n\
        This is linker for "TARGET_ARCH_NAME" CPU that can be used\n\
    to link multiple object files into one executable file. Linker\n\
    also does support static libraries generated by archiver.\n\
\n\
Arguments:\n\
    -h --help           Print this help.\n\
       --version        Print version number and exit.\n\
\n"

int main(int argc, char *argv[]){
    arg_parse(argc, argv);
    return 1;
}


static void print_version(void){
    printf("linker for %s CPU %s\n", TARGET_ARCH_NAME, VERSION);
}

static void print_help(void){
    printf(HELP_STRING);
}

static void arg_parse(int argc, char* argv[]){

    for(int i = 1; i<argc; i++){
        if(strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0 ){
            print_help();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "--version") == 0 ){
            print_version();
            exit(EXIT_SUCCESS);
        }
        else{
            fprintf(stderr, "Wrong arg format!\n");
            exit(EXIT_FAILURE);
        }
    }

}
