/**
 * @file linker.c
 *
 * @brief Portable linker from m2tools.
 *
 * @author Bc. Vladislav Mlejnecký <v.mlejnecky@seznam.cz>
 *
 * @note This file is part of m2tools project.
 *
 * Linker is splitted into multiple files:
 *  - ldparser.c
 *  - ldparser.h
 *  - linker.c
 *  - linker_util.c
 *  - linker_util.h
 *  - ln_section_list.c
 *  - ln_section_lish.h
 *  - ln_symbol_list.c
 *  - ln_symbol_list.h
 *
 * @todo finish linker
 * @todo add date when finished
 *
 * Linker is configured via linker script file. This file have simple syntax.
 * Main purporse of configuration is to decide wich section goes into wich memory.
 * Also, is possible to set entry point and define symbols. This can be used to
 * define for example where RAM end a use this symbol in stack initialization routine.
 *
 * Following commands are supported:
 *
 * MEM name size orig
 *      This is used to define new memory. Name is used by PUT command, size can
 *      use 'k' and 'M' postfix and have to be decimal number, orig have to be
 *      in format that will be parsed succesfully by sscanf and SCNisa_addr_t
 *      defined in isa library.
 *
 * PUT section_name mem_name
 *      PUT will place section into specified memory. Memory have to be defined
 *      before calling PUT. In section name using '*' is possible as usual.
 *
 * SET symbol_name symbol_value
 *      Set will create new symbol with absolute value and place it into global
 *      symbol table. It can be used to define memory boundaries. Format of
 *      symbol_value have to be as defined by isa library and is parsed by
 *      sscanf and SCNisa_addr_t.
 *
 * ENT symbol
 *      This command can be called only once. It is used to specify where
 *      loader should jump when starting linked program. Symbol have to be defined
 *      and exported.
 *
 * Example of linker file:
 *
 *      ;set entry point
 *      ENT crt0
 *      ;create two memory
 *      MEM RAM_0 1k 0x000400
 *      MEM ROM_0 256 0x000000
 *      ;create symbols with memory boundaries
 *      SET RAM_0_START 0x000400
 *      SET RAM_0_END 0x0007ff
 *      ;place sections
 *      PUT .text ROM_0
 *      PUT .bss RAM_0
 *      PUT .data RAM_0
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

#include "ldparser.h"
#include "ln_section_list.h"
#include "ln_symbol_list.h"

#include <isa.h>
#include <ldm.h>
#include <obj.h>
#include <sl.h>

static void print_version(void);
static void print_help(void);
static void arg_parse(int argc, char* argv[]);
static void clean_mem(void);

#ifndef NDEBUG
void print_settings(void);
#endif

typedef struct{
    char **libs;
    char **obj_files;
    char *output_filename;
    char *linker_script;
    unsigned int libs_count;
    unsigned int obj_count;
}settings_t;

static settings_t settings;
ldm_file_t *finalLDM = NULL;
lds_t *lds = NULL;

#define HELP_STRING "\
Example usage: \n\
 "PROG_NAME" -o out.ldm -T linker.ld -l my_lib.sl main.o\n\
\n\
        This is linker for "TARGET_ARCH_NAME" CPU that can be used\n\
    to link multiple object files into one executable file. Linker\n\
    also does support static libraries generated by archiver.\n\
\n\
Arguments:\n\
    -h --help           Print this help.\n\
       --version        Print version number and exit.\n\
    -l                  Link static library, have to be followed by path.\n\
    -o --output         Set output filename, have to be followed by name.\n\
    -T                  Path to the linker script.\n\
\n"

int main(int argc, char *argv[]){

    atexit(clean_mem);

    //get arguments
    arg_parse(argc, argv);

    #ifndef NDEBUG
    print_settings();
    #endif

    // parse linker script
    lds = parse_lds(settings.linker_script);

    #ifndef NDEBUG
    print_lds(lds);
    #endif

    //create LDM structure
    if(new_ldm_file(&finalLDM, settings.output_filename) != true){
        fprintf(stderr, "Failed to create LDM file struct! ldmlib errno: %d\n", get_ldmlib_errno());
        exit(EXIT_FAILURE);
    }

    mem_t *head = lds->first_mem;

    if(head == NULL){
        fprintf(stderr, "There is no memory defined in the LDS file!\n");
        exit(EXIT_FAILURE);
    }

    while(head != NULL){
        ldm_mem_t *tmp_mem = NULL;

        if(new_mem(&tmp_mem, head->name, head->orig, head->size) != true){
            fprintf(stderr, "Failed to create memory item %s. ldmlib errno: %d\n", head->name, get_ldmlib_errno());
            exit(EXIT_FAILURE);
        }

        if(append_mem_into_file(tmp_mem, finalLDM) != true){
            fprintf(stderr, "Failed to append memory item %s into LDM file! ldmlib errno: %d\n", head->name, get_ldmlib_errno());
            exit(EXIT_FAILURE);
        }

        head = head->next;
    }

    //create cashe with all sections - later we will work with that cashe
    //first - object files
    for(unsigned int i = 0; i < settings.obj_count; i++){
        obj_file_t *tmp_obj = NULL;

        if(!obj_load_from_file(settings.obj_files[i], &tmp_obj)){
            fprintf(stderr, "Failed to load obj file '%s'! objlib errno: %d\n", settings.obj_files[i], get_objlib_errno());
            exit(EXIT_FAILURE);
        }

        if(!append_into_section_list_obj(tmp_obj)){
            fprintf(stderr, "Failed to append object file '%s' into cashe! ", settings.obj_files[i]);

            if(get_section_list_errno() == SECTION_OBJLIB_ERROR)
                fprintf(stderr, "Error in objlib, errno: %d\n", get_objlib_errno());
            else if(get_section_list_errno() == SECTION_ISALIB_ERROR)
                fprintf(stderr, "Error in isalib, errno: %d\n", get_isalib_errno());
            else
                fprintf(stderr, "section list errno: %d\n", get_section_list_errno());

            exit(EXIT_FAILURE);
        }

        free_object_file(tmp_obj);
    }

    //then libraries
    for(unsigned int i = 0; i < settings.libs_count; i++){
        static_library_t *tmp_sl = NULL;

        if(!sl_load(settings.libs[i], &tmp_sl)){
            fprintf(stderr, "Failed to load static library '%s'! sllib errno: %d\n", settings.libs[i], get_sllib_errno());
            exit(EXIT_FAILURE);
        }

        if(!append_into_section_list_sl(tmp_sl)){
            fprintf(stderr, "Failed to append static library '%s' into cashe! ", settings.libs[i]);

            if(get_section_list_errno() == SECTION_OBJLIB_ERROR)
                fprintf(stderr, "Error in objlib, errno: %d\n", get_objlib_errno());
            else if(get_section_list_errno() == SECTION_ISALIB_ERROR)
                fprintf(stderr, "Error in isalib, errno: %d\n", get_isalib_errno());
            else
                fprintf(stderr, "section list errno: %d\n", get_section_list_errno());

            exit(EXIT_FAILURE);
        }

        free_sl(tmp_sl);
    }

    #ifndef NDEBUG
    print_section_list();
    #endif

    //build symbol table
    for(section_list_item_t *head = first_section_item; head != NULL; head = head->next){
        if(!parse_symbols(head)){
            fprintf(stderr, "Error in symbol list, errno: %d\n", get_symbol_list_errno());
            exit(EXIT_FAILURE);
        }
    }

    #ifndef NDEBUG
    print_symbols_lists();
    #endif

    return 1;
}


static void print_version(void){
    printf("linker for %s CPU %s\n", TARGET_ARCH_NAME, VERSION);
}

static void print_help(void){
    printf(HELP_STRING);
}

static void arg_parse(int argc, char* argv[]){

    settings.libs = NULL;
    settings.libs_count = 0;
    settings.obj_files = NULL;
    settings.obj_count = 0;
    settings.output_filename = NULL;
    settings.linker_script = NULL;

    for(int i = 1; i<argc; i++){
        if(strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0 ){
            print_help();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "--version") == 0 ){
            print_version();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0){
            if(settings.output_filename != NULL){
                fprintf(stderr, "Too much output files given!\n");
                exit(EXIT_FAILURE);
            }
            else if((i+1)<argc){
                settings.output_filename = argv[++i];
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
        else if(strcmp(argv[i], "-T") == 0){
            if(settings.linker_script != NULL){
                fprintf(stderr, "Too much output files given!\n");
                exit(EXIT_FAILURE);
            }
            else if ((i+1)<argc){
                settings.linker_script = argv[++i];
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
        else if(strcmp(argv[i], "-l") == 0){
            if((i+1)<argc){
                char **new_ptr = (char **) realloc((void **)settings.libs, sizeof(char **) * (settings.libs_count + 1));

                if(new_ptr != NULL){
                    settings.libs = new_ptr;
                    settings.libs[settings.libs_count++] = argv[++i];
                }
                else{
                    fprintf(stderr, "Realloc failed!\n");
                    exit(EXIT_FAILURE);
                }
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
        else{
            if(*(argv[i]) == '-'){
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
            else{
                char **new_ptr = (char **) realloc((void **)settings.obj_files, sizeof(char **) * (settings.obj_count + 1));

                if(new_ptr != NULL){
                    settings.obj_files = new_ptr;
                    settings.obj_files[settings.obj_count++] = argv[i];
                }
                else{
                    fprintf(stderr, "Realloc failed!\n");
                    exit(EXIT_FAILURE);
                }
            }
        }
    }

    if(settings.linker_script == NULL){
        fprintf(stderr, "Missing linker script path!\n");
        exit(EXIT_FAILURE);
    }

    if(settings.obj_count == 0 && settings.libs_count == 0){
        fprintf(stderr, "Given zero libs and zero object, nothink to link!\n");
        exit(EXIT_FAILURE);
    }

    if(settings.output_filename == NULL){
        fprintf(stderr, "Missing output filename!\n");
        exit(EXIT_FAILURE);
    }

}

static void clean_mem(void){
    if(settings.obj_files != NULL){
        free(settings.obj_files);
    }

    if(settings.libs != NULL){
        free(settings.libs);
    }

    if(finalLDM != NULL){
        free_ldm_file_struct(finalLDM);
    }

    if(lds != NULL){
        free_lds(lds);
    }

    if(first_section_item != NULL){
        clean_up_section_list();
    }

    if(exported_symbols != NULL || imported_symbols != NULL){
        clean_up_symbol_lists();
    }
}

#ifndef NDEBUG
void print_settings(void){
    printf("Settings:\n");

    printf("|- Linker script: '%s'\n", settings.linker_script);
    printf("|- Output name: '%s'\n", settings.output_filename);

    if(settings.libs_count == 0){
        printf("|- Static libs: (null)\n");
    }
    else{
        printf("|- Static libs: %d\n", settings.libs_count);

        for(unsigned int i = 0; i < settings.libs_count - 1; i++){
            printf("|  |- '%s'\n", settings.libs[i]);
        }
        printf("|  '- '%s'\n", settings.libs[settings.libs_count - 1]);
    }

    if(settings.obj_count == 0){
        printf("'- Object files: (null)\n");
    }
    else{
        printf("'- Object files: %d\n", settings.obj_count);

        for(unsigned int i = 0; i < settings.obj_count - 1; i++){
            printf("   |- '%s'\n", settings.obj_files[i]);
        }
        printf("   '- '%s'\n", settings.obj_files[settings.obj_count - 1]);
    }
}
#endif
