/**
 * @file linker.c
 *
 * @brief Tool for linking object files together.
 *
 * @author Bc. Vladislav Mlejnecký <v.mlejnecky@seznam.cz>
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

static void print_version(void);
static void print_help(void);
static void arg_parse(int argc, char* argv[]);
static void clean_mem(void);

typedef struct{
    char **libs;
    char **obj_files;
    char *output_filename;
    char *linker_script;
    unsigned int libs_count;
    unsigned int obj_count;
}settings_t;

static settings_t settings;

#define HELP_STRING "\
Example usage: \n\
 "PROG_NAME" -o out.ldm -T linker.ld -l my_lib.sl main.o\n\
\n\
        This is linker for "TARGET_ARCH_NAME" CPU that can be used\n\
    to link multiple object files into one executable file. Linker\n\
    also does support static libraries generated by archiver.\n\
\n\
Arguments:\n\
    -h --help           Print this help.\n\
       --version        Print version number and exit.\n\
    -l                  Link static library, have to be followed by path.\n\
    -o --output         Set output filenamem have to be followed by filename.\n\
    -T                  Path to the linker script.\n\
\n"

int main(int argc, char *argv[]){

    atexit(clean_mem);

    //get arguments
    arg_parse(argc, argv);

    printf("libs_count: %d \t obj_count: %d \t out_filename: %s\n", settings.libs_count, settings.obj_count, settings.output_filename);

    printf("libs:\n");

    for(unsigned int i = 0; i < settings.libs_count; i++){
        printf("%s\n", settings.libs[i]);
    }

    printf("objs:\n");

    for(unsigned int i = 0; i < settings.obj_count; i++){
        printf("%s\n", settings.obj_files[i]);
    }

    return 1;
}


static void print_version(void){
    printf("linker for %s CPU %s\n", TARGET_ARCH_NAME, VERSION);
}

static void print_help(void){
    printf(HELP_STRING);
}

static void arg_parse(int argc, char* argv[]){

    settings.libs = NULL;
    settings.libs_count = 0;
    settings.obj_files = NULL;
    settings.obj_count = 0;
    settings.output_filename = NULL;
    settings.linker_script = NULL;

    for(int i = 1; i<argc; i++){
        if(strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0 ){
            print_help();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "--version") == 0 ){
            print_version();
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0){
            if(settings.output_filename != NULL){
                fprintf(stderr, "Too much output files given!\n");
                exit(EXIT_FAILURE);
            }
            else if((i+1)<argc){
                settings.output_filename = argv[++i];
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
        else if(strcmp(argv[i], "-T") == 0){
            if(settings.linker_script != NULL){
                fprintf(stderr, "Too much output files given!\n");
                exit(EXIT_FAILURE);
            }
            else if ((i+1)<argc){
                settings.linker_script = argv[++i];
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
        else if(strcmp(argv[i], "-l") == 0){
            if((i+1)<argc){
                char **new_ptr = (char **) realloc((void **)settings.libs, sizeof(char **) * (settings.libs_count + 1));

                if(new_ptr != NULL){
                    settings.libs = new_ptr;
                    settings.libs[settings.libs_count++] = argv[++i];
                }
                else{
                    fprintf(stderr, "Realloc failed!\n");
                    exit(EXIT_FAILURE);
                }
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
        else{
            if(*(argv[i]) == '-'){
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
            else{
                char **new_ptr = (char **) realloc((void **)settings.obj_files, sizeof(char **) * (settings.obj_count + 1));

                if(new_ptr != NULL){
                    settings.obj_files = new_ptr;
                    settings.obj_files[settings.obj_count++] = argv[i];
                }
                else{
                    fprintf(stderr, "Realloc failed!\n");
                    exit(EXIT_FAILURE);
                }
            }
        }
    }

    if(settings.linker_script == NULL){
        fprintf(stderr, "Missing linker script path!\n");
        exit(EXIT_FAILURE);
    }

    if(settings.obj_count == 0 && settings.libs_count == 0){
        fprintf(stderr, "Given zero libs and zero object, nothink to link!\n");
        exit(EXIT_FAILURE);
    }

    if(settings.output_filename == NULL){
        fprintf(stderr, "Missing output filename!\n");
        exit(EXIT_FAILURE);
    }

}

static void clean_mem(void){
    if(settings.obj_files != NULL){
        free(settings.obj_files);
    }

    if(settings.libs != NULL){
        free(settings.libs);
    }
}
