#include "instructions_description.h"

#include "../../src/platformlib_common.h"
#include "../../src/platformlib_private.h"

#include "opcode_decode.h"

#include <stddef.h>

instruction_signature_t platformlib_instruction_signatures[] = {
    {"MOV",  2, 1, INSTRU_MOV,  MOV_BASE },
    {"MVI",  2, 2, INSTRU_MVI,  MVI_BASE },
    {"LXI",  2, 3, INSTRU_LXI,  LXI_BASE },
    {"LDA",  1, 3, INSTRU_LDA,  LDA_BASE },
    {"STA",  1, 3, INSTRU_STA,  STA_BASE },
    {"LHLD", 1, 3, INSTRU_LHLD, LHLD_BASE},
    {"SHLD", 1, 3, INSTRU_SHLD, SHLD_BASE},
    {"LDAX", 1, 1, INSTRU_LDAX, LDAX_BASE},
    {"STAX", 1, 1, INSTRU_STAX, STAX_BASE},
    {"XCHG", 0, 1, INSTRU_XCHG, XCHG_BASE},
    {"ADD",  1, 1, INSTRU_ADD,  ADD_BASE },
    {"ADI",  1, 2, INSTRU_ADI,  ADI_BASE },
    {"ADC",  1, 1, INSTRU_ADC,  ADC_BASE },
    {"ACI",  1, 2, INSTRU_ACI,  ACI_BASE },
    {"SUB",  1, 1, INSTRU_SUB,  SUB_BASE },
    {"SUI",  1, 2, INSTRU_SUI,  SUI_BASE },
    {"SBB",  1, 1, INSTRU_SBB,  SBB_BASE },
    {"SBI",  1, 2, INSTRU_SBI,  SBI_BASE },
    {"INR",  1, 1, INSTRU_INR,  INR_BASE },
    {"DCR",  1, 1, INSTRU_DCR,  DCR_BASE },
    {"INX",  1, 1, INSTRU_INX,  INX_BASE },
    {"DCX",  1, 1, INSTRU_DCX,  DCX_BASE },
    {"DAD",  1, 1, INSTRU_DAD,  DAD_BASE },
    {"DAA",  0, 1, INSTRU_DAA,  DAA_BASE },
    {"ANA",  1, 1, INSTRU_ANA,  ANA_BASE },
    {"ANI",  1, 2, INSTRU_ANI,  ANI_BASE },
    {"ORA",  1, 1, INSTRU_ORA,  ORA_BASE },
    {"ORI",  1, 2, INSTRU_ORI,  ORI_BASE },
    {"XRA",  1, 1, INSTRU_XRA,  XRA_BASE },
    {"XRI",  1, 2, INSTRU_XRI,  XRI_BASE },
    {"CMP",  1, 1, INSTRU_CMP,  CMP_BASE },
    {"CPI",  1, 2, INSTRU_CPI,  CPI_BASE },
    {"RLC",  0, 1, INSTRU_RLC,  RLC_BASE },
    {"RRC",  0, 1, INSTRU_RRC,  RRC_BASE },
    {"RAL",  0, 1, INSTRU_RAL,  RAL_BASE },
    {"RAR",  0, 1, INSTRU_RAR,  RAR_BASE },
    {"CMA",  0, 1, INSTRU_CMA,  CMA_BASE },
    {"CMC",  0, 1, INSTRU_CMC,  CMC_BASE },
    {"STC",  0, 1, INSTRU_STC,  STC_BASE },
    {"JMP",  1, 3, INSTRU_JMP,  JMP_BASE },
    {"JNZ",  1, 3, INSTRU_JNZ,  Jccc_BASE | SHIFT_TO_CCC(CCC_NZ_CODE)},
    {"JZ",   1, 3, INSTRU_JZ,   Jccc_BASE | SHIFT_TO_CCC(CCC_Z_CODE) },
    {"JNC",  1, 3, INSTRU_JNC,  Jccc_BASE | SHIFT_TO_CCC(CCC_NC_CODE)},
    {"JC",   1, 3, INSTRU_JC,   Jccc_BASE | SHIFT_TO_CCC(CCC_C_CODE) },
    {"JPO",  1, 3, INSTRU_JPO,  Jccc_BASE | SHIFT_TO_CCC(CCC_PO_CODE)},
    {"JPE",  1, 3, INSTRU_JPE,  Jccc_BASE | SHIFT_TO_CCC(CCC_PE_CODE)},
    {"JP",   1, 3, INSTRU_JP,   Jccc_BASE | SHIFT_TO_CCC(CCC_P_CODE) },
    {"JM",   1, 3, INSTRU_JM,   Jccc_BASE | SHIFT_TO_CCC(CCC_M_CODE) },
    {"CALL", 1, 3, INSTRU_CALL, CALL_BASE},
    {"CNZ",  1, 3, INSTRU_CNZ,  Cccc_BASE | SHIFT_TO_CCC(CCC_NZ_CODE)},
    {"CZ",   1, 3, INSTRU_CZ,   Cccc_BASE | SHIFT_TO_CCC(CCC_Z_CODE) },
    {"CNC",  1, 3, INSTRU_CNC,  Cccc_BASE | SHIFT_TO_CCC(CCC_NC_CODE)},
    {"CC",   1, 3, INSTRU_CC,   Cccc_BASE | SHIFT_TO_CCC(CCC_C_CODE) },
    {"CPO",  1, 3, INSTRU_CPO,  Cccc_BASE | SHIFT_TO_CCC(CCC_PO_CODE)},
    {"CPE",  1, 3, INSTRU_CPE,  Cccc_BASE | SHIFT_TO_CCC(CCC_PE_CODE)},
    {"CP",   1, 3, INSTRU_CP,   Cccc_BASE | SHIFT_TO_CCC(CCC_P_CODE) },
    {"CM",   1, 3, INSTRU_CM,   Cccc_BASE | SHIFT_TO_CCC(CCC_M_CODE) },
    {"RET",  0, 1, INSTRU_RET,  RET_BASE},
    {"RNZ",  0, 1, INSTRU_RNZ,  Rcc_BASE | SHIFT_TO_CCC(CCC_NZ_CODE)},
    {"RZ",   0, 1, INSTRU_RZ,   Rcc_BASE | SHIFT_TO_CCC(CCC_Z_CODE) },
    {"RNC",  0, 1, INSTRU_RNC,  Rcc_BASE | SHIFT_TO_CCC(CCC_NC_CODE)},
    {"RC",   0, 1, INSTRU_RC,   Rcc_BASE | SHIFT_TO_CCC(CCC_C_CODE) },
    {"RPO",  0, 1, INSTRU_RPO,  Rcc_BASE | SHIFT_TO_CCC(CCC_PO_CODE)},
    {"RPE",  0, 1, INSTRU_RPE,  Rcc_BASE | SHIFT_TO_CCC(CCC_PE_CODE)},
    {"RP",   0, 1, INSTRU_RP,   Rcc_BASE | SHIFT_TO_CCC(CCC_P_CODE) },
    {"RM",   0, 1, INSTRU_RM,   Rcc_BASE | SHIFT_TO_CCC(CCC_M_CODE) },
    {"RST",  1, 1, INSTRU_RST,  RST_BASE},
    {"PCHL", 0, 1, INSTRU_PCHL, PCHL_BASE},
    {"PUSH", 1, 1, INSTRU_PUSH, PUSH_BASE},
    {"POP",  1, 1, INSTRU_POP,  POP_BASE},
    {"XTHL", 0, 1, INSTRU_XTHL, XTHL_BASE},
    {"SPHL", 0, 1, INSTRU_SPHL, SPHL_BASE},
    {"IN",   1, 2, INSTRU_IN,   IN_BASE},
    {"OUT",  1, 2, INSTRU_OUT,  OUT_BASE},
    {"EI",   0, 1, INSTRU_EI,   EI_BASE},
    {"DI",   0, 1, INSTRU_DI,   DI_BASE},
    {"HLT",  0, 1, INSTRU_HLT,  HLT_BASE},
    {"NOP",  0, 1, INSTRU_NOP,  NOP_BASE},
    {NULL,   0, 1, INSTRU_UNKOWN, 0}
};
