#define _GNU_SOURCE

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <obj.h>
#include <isa.h>

typedef struct{
    char *i_file;
    char *i_file_abs;
}settings_t;

#define HELP_STRING "\
Example usage: %s main.o\n\
\n\
        This is simple objdump utility for MARK-II CPU that can be used\n\
    to show content of object files generated by assembler.\n\
\n\
Arguments:\n\
    -h --help           Print this help.\n\
       --version        Print version number and exit.\n"

static void arg_parse(int argc, char* argv[]);
static void print_version(void);
static void print_help(char *cmd_name);
static void clean_mem(void);

static settings_t settings;
obj_file_t *obj_file = NULL;

int main(int argc, char* argv[]){

    atexit(clean_mem);

    //get args
    settings.i_file = NULL;
    settings.i_file_abs = NULL;

    arg_parse(argc, argv);

    settings.i_file_abs = canonicalize_file_name(settings.i_file);

    if(settings.i_file_abs == NULL){
        fprintf(stderr, "Failed to get abs filepath for input file!\n");
        exit(EXIT_FAILURE);
    }

    if(obj_load(settings.i_file_abs, &obj_file) != 0){
        fprintf(stderr, "Failed to load object file! obj_lib errno: %d\n", get_objlib_errno());
        exit(EXIT_FAILURE);
    }

    printf("Object file from: '%s'\n", settings.i_file_abs);

    printf(" |- File name: '%s'\n", obj_file->object_file_name);

    for(section_t* section = obj_file->first_section; section != NULL; section = section->next){
        if(section->next != NULL){
            printf(" |- Section: '%s'\n", section->section_name);
        }
        else{
            printf(" '- Section: '%s'\n", section->section_name);
        }
    }

    return EXIT_SUCCESS;
}

static void arg_parse(int argc, char* argv[]){
    int file_given = 0;
    int toomuchfiles_given = 0;

    for(int i = 1; i<argc; i++){
        if(strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0 ){
            print_help(basename(argv[0]));
            exit(EXIT_SUCCESS);
        }
        else if(strcmp(argv[i], "--version") == 0 ){
            print_version();
            exit(EXIT_SUCCESS);
        }
        else{
            if(argv[i][0] != '-'){
                if(file_given == 0){
                    settings.i_file = argv[i];
                    file_given = 1;
                }
                else{
                    toomuchfiles_given = 1;
                }
            }
            else{
                fprintf(stderr, "Wrong arg format!\n");
                exit(EXIT_FAILURE);
            }
        }
    }

    if(file_given == 0){
        fprintf(stderr, "Missing input file!\n");
        exit(EXIT_FAILURE);
    }
    if(toomuchfiles_given == 1){
        fprintf(stderr, "Too much input files given!\n");
        exit(EXIT_FAILURE);
    }

}

static void print_version(void){
    printf("objdump for MARK-II CPU %s\n", VERSION);
}

static void print_help(char *cmd_name){
    printf(HELP_STRING, cmd_name);
}

static void clean_mem(void){
    if(obj_file != NULL){
        free_object_file(obj_file);
    }
    if(settings.i_file_abs != NULL){
        free(settings.i_file_abs);
    }
}
